version: '3.8'

services:
  op-api:
    image: node:20
    container_name: op-api
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
