apiVersion: apps/v1
kind: Deployment
metadata:
  name: opadi-frontend
  labels:
    app: opadi-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opadi-frontend
  template:
    metadata:
      labels:
        app: opadi-frontend
    spec:
      containers:
      - name: opadi-frontend
        image: robleslf/opadi-frontend:latest
        ports:
        - containerPort: 80
