api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: tu@email.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web
