name: Deploy Backend OP-API

on:
  push:
    branches:
      - main
    paths:
      - 'opadi-api/**'
      - '.github/workflows/deploy-backend.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for Backend
        uses: docker/build-push-action@v5
        with:
          context: ./opadi-api
          file: ./opadi-api/Dockerfile
          push: true
          tags: robleslf/opadi-api:latest,robleslf/opadi-api:${{ github.sha }}
